# Generated by Django 4.2.3 on 2023-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("no_of_guests", models.SmallIntegerField()),
                ("bookingDate", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="menu", name="title", field=models.CharField(max_length=255),
        ),
    ]
